/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ns_utils_natives__NL */

#ifndef _Included_ns_utils_natives__NL
#define _Included_ns_utils_natives__NL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ns_utils_natives__NL
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_ns_utils_natives__1NL_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
