/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ns_utils_natives_NL_LINUX_ENV */

#ifndef _Included_ns_utils_natives_NL_LINUX_ENV
#define _Included_ns_utils_natives_NL_LINUX_ENV
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ns_utils_natives_NL_LINUX_ENV
 * Method:    call
 * Signature: (Lns/utils/natives/Method;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_ns_utils_natives_NL_1LINUX_1ENV_call
  (JNIEnv *, jobject, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
